[package]
name = "update-bindings"
version = "1.0.0"
publish = false

edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true


[dependencies]
convert_case = "0.6"
proc-macro2 = "1.0"
quote = "1.0"
regex = "1.0"
syn = "2.0"
thiserror = "2.0"
